name: FiledPlugin
main: com.filed.FiledPlugin
version: 1.3-SNAPSHOT
description: A plugin to download files to various directories and support non-direct links.
commands:
  filed:
    description: Main command for FiledPlugin.
    usage: /filed <download|reload|list> [args]