name: FILED
main: com.hanz.filed.filedmain
version: 1.0
api-version: 1.20
description: A plugin to download files and YouTube videos
author: Fahryanak
commands:
  filed:
    description: FILED plugin commands
    usage: /filed <down|reload>