name: FILED
version: 1.2.1
main: com.example.downloadplugin.DownloadPlugin
description: Enhanced plugin to download files from various sources
author: Fahryanak
api-version: 1.21
commands:
  filed:
    description: Manage FILED plugin
    usage: /<command> <reload|download>