name: Build and Deploy

on:
  push:
    paths:
      - trigger.txt  # Ganti dengan nama file yang Anda inginkan sebagai trigger
  pull_request:
    paths:
      - trigger.txt  # Ganti dengan nama file yang Anda inginkan sebagai trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Ganti dengan versi Java yang Anda gunakan
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: filed-plugin
          path: target/*.jar  # Menyimpan semua file JAR yang dihasilkan
