name: Build and Deploy

on:
  push:
    paths:
      - trigger.txt  # Ganti dengan nama file yang Anda inginkan sebagai trigger
  pull_request:
    paths:
      - trigger.txt  # Ganti dengan nama file yang Anda inginkan sebagai trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin'
         java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: filed-plugin
          path: target/*.jar  # Menyimpan semua file JAR yang dihasilkan
